# Generated by Django 6.0.1 on 2026-03-24 17:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('potable', models.BooleanField(blank=True, null=True)),
                ('caudal', models.FloatField(blank=True, null=True)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25830)),
            ],
            options={
                'db_table': 'd"."fuentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('dificultad', models.CharField(blank=True, max_length=50, null=True)),
                ('desnivel', models.IntegerField(blank=True, null=True)),
                ('abierta', models.BooleanField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=25830)),
            ],
            options={
                'db_table': 'd"."rutas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('abierto', models.BooleanField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25830)),
            ],
            options={
                'db_table': 'd"."zonas',
                'managed': False,
            },
        ),
    ]
